replicaCount: 1

image:
  repository: harbor.k8s.labs.itmo.loc/public/my-fastapi-app
  pullPolicy: IfNotPresent
  tag: "1.0.1"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: my-app.k8s.labs.itmo.loc
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: k8s-labs-itmo-loc-tls # Используем тот же секрет
     hosts:
       - my-app.k8s.labs.itmo.loc

# Переменные окружения для нашего приложения
appConfig:
  REDIS_HOST: redis-master.default.svc.cluster.local
  QDRANT_HOST: qdrant.default.svc.cluster.local
